// Generated by Tools/generate_app_server_requests.py. Do not edit by hand.
// Regenerate with Tools/regenerate.sh; verify with Tools/check_drift.sh.
import Foundation

/// The three wire representations allowed by nullable app-server parameters.
///
/// This is intentionally not `Optional`: an omitted JSON-RPC `params` member,
/// an explicit JSON null, and an encoded value are three distinct protocol
/// states while the app-server API is experimental.
public enum CodexNullableRequestParameters<Value: Encodable & Sendable>: Sendable {
    case omitted
    case null
    case value(Value)
}

/// A sealed compile-time pairing of one app-server method and response.
///
/// Its initializer is module-internal: external callers can only obtain a
/// value from generated `CodexRequest` factories, so they cannot forge a false
/// method/response pairing or bypass specialized lifecycle commands.
public struct CodexAppServerRequest<Response: Decodable & Sendable>: Sendable {
    public let method: CodexAppServerClientMethod
    private let parameterEncoder: @Sendable () throws -> CodexJSONValue?

    private init(
        method: CodexAppServerClientMethod,
        parameterEncoder: @escaping @Sendable () throws -> CodexJSONValue?
    ) {
        self.method = method
        self.parameterEncoder = parameterEncoder
    }

    fileprivate static func required<Parameters: Encodable & Sendable>(
        method: CodexAppServerClientMethod,
        params: Parameters
    ) -> Self {
        Self(method: method) { try CodexJSONValue(encoding: params) }
    }

    fileprivate static func omitted(method: CodexAppServerClientMethod) -> Self {
        Self(method: method) { nil }
    }

    fileprivate static func nullable<Parameters: Encodable & Sendable>(
        method: CodexAppServerClientMethod,
        params: CodexNullableRequestParameters<Parameters>
    ) -> Self {
        Self(method: method) {
            switch params {
            case .omitted: nil
            case .null: .null
            case .value(let value): try CodexJSONValue(encoding: value)
            }
        }
    }

    func encodeParameters() throws -> CodexJSONValue? {
        try parameterEncoder()
    }
}

/// Namespace for generated, protocol-native app-server request factories.
public enum CodexRequest {}

extension CodexRequest {
    public static func serverDiagnostics(
        _ params: CodexSchemaServerDiagnosticsParams
    ) -> CodexAppServerRequest<CodexSchemaServerDiagnosticsResponse> {
        .required(method: .serverDiagnostics, params: params)
    }
}
extension CodexRequest {
    static func threadStart(
        _ params: CodexSchemaThreadStartParams
    ) -> CodexAppServerRequest<CodexSchemaThreadStartResponse> {
        .required(method: .threadStart, params: params)
    }
}
extension CodexRequest {
    static func threadResume(
        _ params: CodexSchemaThreadResumeParams
    ) -> CodexAppServerRequest<CodexSchemaThreadResumeResponse> {
        .required(method: .threadResume, params: params)
    }
}
extension CodexRequest {
    static func threadFork(
        _ params: CodexSchemaThreadForkParams
    ) -> CodexAppServerRequest<CodexSchemaThreadForkResponse> {
        .required(method: .threadFork, params: params)
    }
}
extension CodexRequest {
    public static func threadArchive(
        _ params: CodexSchemaThreadArchiveParams
    ) -> CodexAppServerRequest<CodexSchemaThreadArchiveResponse> {
        .required(method: .threadArchive, params: params)
    }
}
extension CodexRequest {
    public static func threadDelete(
        _ params: CodexSchemaThreadDeleteParams
    ) -> CodexAppServerRequest<CodexSchemaThreadDeleteResponse> {
        .required(method: .threadDelete, params: params)
    }
}
extension CodexRequest {
    static func threadUnsubscribe(
        _ params: CodexSchemaThreadUnsubscribeParams
    ) -> CodexAppServerRequest<CodexSchemaThreadUnsubscribeResponse> {
        .required(method: .threadUnsubscribe, params: params)
    }
}
extension CodexRequest {
    public static func threadIncrementElicitation(
        _ params: CodexSchemaThreadIncrementElicitationParams
    ) -> CodexAppServerRequest<CodexSchemaThreadIncrementElicitationResponse> {
        .required(method: .threadIncrementElicitation, params: params)
    }
}
extension CodexRequest {
    public static func threadDecrementElicitation(
        _ params: CodexSchemaThreadDecrementElicitationParams
    ) -> CodexAppServerRequest<CodexSchemaThreadDecrementElicitationResponse> {
        .required(method: .threadDecrementElicitation, params: params)
    }
}
extension CodexRequest {
    public static func threadNameSet(
        _ params: CodexSchemaThreadSetNameParams
    ) -> CodexAppServerRequest<CodexSchemaThreadSetNameResponse> {
        .required(method: .threadNameSet, params: params)
    }
}
extension CodexRequest {
    public static func threadGoalSet(
        _ params: CodexSchemaThreadGoalSetParams
    ) -> CodexAppServerRequest<CodexSchemaThreadGoalSetResponse> {
        .required(method: .threadGoalSet, params: params)
    }
}
extension CodexRequest {
    public static func threadGoalGet(
        _ params: CodexSchemaThreadGoalGetParams
    ) -> CodexAppServerRequest<CodexSchemaThreadGoalGetResponse> {
        .required(method: .threadGoalGet, params: params)
    }
}
extension CodexRequest {
    public static func threadGoalClear(
        _ params: CodexSchemaThreadGoalClearParams
    ) -> CodexAppServerRequest<CodexSchemaThreadGoalClearResponse> {
        .required(method: .threadGoalClear, params: params)
    }
}
extension CodexRequest {
    public static func threadQueueAdd(
        _ params: CodexSchemaThreadQueueAddParams
    ) -> CodexAppServerRequest<CodexSchemaThreadQueueAddResponse> {
        .required(method: .threadQueueAdd, params: params)
    }
}
extension CodexRequest {
    public static func threadQueueList(
        _ params: CodexSchemaThreadQueueListParams
    ) -> CodexAppServerRequest<CodexSchemaThreadQueueListResponse> {
        .required(method: .threadQueueList, params: params)
    }
}
extension CodexRequest {
    public static func threadQueueUpdate(
        _ params: CodexSchemaThreadQueueUpdateParams
    ) -> CodexAppServerRequest<CodexSchemaThreadQueueUpdateResponse> {
        .required(method: .threadQueueUpdate, params: params)
    }
}
extension CodexRequest {
    public static func threadQueueDelete(
        _ params: CodexSchemaThreadQueueDeleteParams
    ) -> CodexAppServerRequest<CodexSchemaThreadQueueDeleteResponse> {
        .required(method: .threadQueueDelete, params: params)
    }
}
extension CodexRequest {
    public static func threadQueueReorder(
        _ params: CodexSchemaThreadQueueReorderParams
    ) -> CodexAppServerRequest<CodexSchemaThreadQueueReorderResponse> {
        .required(method: .threadQueueReorder, params: params)
    }
}
extension CodexRequest {
    public static func threadQueueStart(
        _ params: CodexSchemaThreadQueueStartParams
    ) -> CodexAppServerRequest<CodexSchemaThreadQueueStartResponse> {
        .required(method: .threadQueueStart, params: params)
    }
}
extension CodexRequest {
    public static func threadMetadataUpdate(
        _ params: CodexSchemaThreadMetadataUpdateParams
    ) -> CodexAppServerRequest<CodexSchemaThreadMetadataUpdateResponse> {
        .required(method: .threadMetadataUpdate, params: params)
    }
}
extension CodexRequest {
    public static func threadSectionMove(
        _ params: CodexSchemaThreadSectionMoveParams
    ) -> CodexAppServerRequest<CodexSchemaThreadSectionMoveResponse> {
        .required(method: .threadSectionMove, params: params)
    }
}
extension CodexRequest {
    public static func threadSettingsUpdate(
        _ params: CodexSchemaThreadSettingsUpdateParams
    ) -> CodexAppServerRequest<CodexSchemaThreadSettingsUpdateResponse> {
        .required(method: .threadSettingsUpdate, params: params)
    }
}
extension CodexRequest {
    public static func threadMemoryModeSet(
        _ params: CodexSchemaThreadMemoryModeSetParams
    ) -> CodexAppServerRequest<CodexSchemaThreadMemoryModeSetResponse> {
        .required(method: .threadMemoryModeSet, params: params)
    }
}
extension CodexRequest {
    public static func memoryReset() -> CodexAppServerRequest<CodexSchemaMemoryResetResponse> {
        .omitted(method: .memoryReset)
    }
}
extension CodexRequest {
    public static func threadUnarchive(
        _ params: CodexSchemaThreadUnarchiveParams
    ) -> CodexAppServerRequest<CodexSchemaThreadUnarchiveResponse> {
        .required(method: .threadUnarchive, params: params)
    }
}
extension CodexRequest {
    public static func threadCompactStart(
        _ params: CodexSchemaThreadCompactStartParams
    ) -> CodexAppServerRequest<CodexSchemaThreadCompactStartResponse> {
        .required(method: .threadCompactStart, params: params)
    }
}
extension CodexRequest {
    public static func threadShellCommand(
        _ params: CodexSchemaThreadShellCommandParams
    ) -> CodexAppServerRequest<CodexSchemaThreadShellCommandResponse> {
        .required(method: .threadShellCommand, params: params)
    }
}
extension CodexRequest {
    public static func threadApproveGuardianDeniedAction(
        _ params: CodexSchemaThreadApproveGuardianDeniedActionParams
    ) -> CodexAppServerRequest<CodexSchemaThreadApproveGuardianDeniedActionResponse> {
        .required(method: .threadApproveGuardianDeniedAction, params: params)
    }
}
extension CodexRequest {
    public static func threadBackgroundTerminalsClean(
        _ params: CodexSchemaThreadBackgroundTerminalsCleanParams
    ) -> CodexAppServerRequest<CodexSchemaThreadBackgroundTerminalsCleanResponse> {
        .required(method: .threadBackgroundTerminalsClean, params: params)
    }
}
extension CodexRequest {
    public static func threadBackgroundTerminalsList(
        _ params: CodexSchemaThreadBackgroundTerminalsListParams
    ) -> CodexAppServerRequest<CodexSchemaThreadBackgroundTerminalsListResponse> {
        .required(method: .threadBackgroundTerminalsList, params: params)
    }
}
extension CodexRequest {
    public static func threadBackgroundTerminalsTerminate(
        _ params: CodexSchemaThreadBackgroundTerminalsTerminateParams
    ) -> CodexAppServerRequest<CodexSchemaThreadBackgroundTerminalsTerminateResponse> {
        .required(method: .threadBackgroundTerminalsTerminate, params: params)
    }
}
extension CodexRequest {
    public static func threadRollback(
        _ params: CodexSchemaThreadRollbackParams
    ) -> CodexAppServerRequest<CodexSchemaThreadRollbackResponse> {
        .required(method: .threadRollback, params: params)
    }
}
extension CodexRequest {
    public static func threadRevert(
        _ params: CodexSchemaThreadRevertParams
    ) -> CodexAppServerRequest<CodexSchemaThreadRevertResponse> {
        .required(method: .threadRevert, params: params)
    }
}
extension CodexRequest {
    public static func threadList(
        _ params: CodexSchemaThreadListParams
    ) -> CodexAppServerRequest<CodexSchemaThreadListResponse> {
        .required(method: .threadList, params: params)
    }
}
extension CodexRequest {
    public static func threadSectionList(
        _ params: CodexSchemaThreadSectionListParams
    ) -> CodexAppServerRequest<CodexSchemaThreadSectionListResponse> {
        .required(method: .threadSectionList, params: params)
    }
}
extension CodexRequest {
    public static func threadSectionCreate(
        _ params: CodexSchemaThreadSectionCreateParams
    ) -> CodexAppServerRequest<CodexSchemaThreadSectionCreateResponse> {
        .required(method: .threadSectionCreate, params: params)
    }
}
extension CodexRequest {
    public static func threadSectionUpdate(
        _ params: CodexSchemaThreadSectionUpdateParams
    ) -> CodexAppServerRequest<CodexSchemaThreadSectionUpdateResponse> {
        .required(method: .threadSectionUpdate, params: params)
    }
}
extension CodexRequest {
    public static func threadSectionDelete(
        _ params: CodexSchemaThreadSectionDeleteParams
    ) -> CodexAppServerRequest<CodexSchemaThreadSectionDeleteResponse> {
        .required(method: .threadSectionDelete, params: params)
    }
}
extension CodexRequest {
    public static func threadSearch(
        _ params: CodexSchemaThreadSearchParams
    ) -> CodexAppServerRequest<CodexSchemaThreadSearchResponse> {
        .required(method: .threadSearch, params: params)
    }
}
extension CodexRequest {
    public static func threadSearchOccurrences(
        _ params: CodexSchemaThreadSearchOccurrencesParams
    ) -> CodexAppServerRequest<CodexSchemaThreadSearchOccurrencesResponse> {
        .required(method: .threadSearchOccurrences, params: params)
    }
}
extension CodexRequest {
    public static func threadLoadedList(
        _ params: CodexSchemaThreadLoadedListParams
    ) -> CodexAppServerRequest<CodexSchemaThreadLoadedListResponse> {
        .required(method: .threadLoadedList, params: params)
    }
}
extension CodexRequest {
    public static func threadRead(
        _ params: CodexSchemaThreadReadParams
    ) -> CodexAppServerRequest<CodexSchemaThreadReadResponse> {
        .required(method: .threadRead, params: params)
    }
}
extension CodexRequest {
    public static func threadTurnsList(
        _ params: CodexSchemaThreadTurnsListParams
    ) -> CodexAppServerRequest<CodexSchemaThreadTurnsListResponse> {
        .required(method: .threadTurnsList, params: params)
    }
}
extension CodexRequest {
    public static func threadItemsList(
        _ params: CodexSchemaThreadItemsListParams
    ) -> CodexAppServerRequest<CodexSchemaThreadItemsListResponse> {
        .required(method: .threadItemsList, params: params)
    }
}
extension CodexRequest {
    public static func threadInjectItems(
        _ params: CodexSchemaThreadInjectItemsParams
    ) -> CodexAppServerRequest<CodexSchemaThreadInjectItemsResponse> {
        .required(method: .threadInjectItems, params: params)
    }
}
extension CodexRequest {
    public static func skillsList(
        _ params: CodexSchemaSkillsListParams
    ) -> CodexAppServerRequest<CodexSchemaSkillsListResponse> {
        .required(method: .skillsList, params: params)
    }
}
extension CodexRequest {
    public static func skillsExtraRootsSet(
        _ params: CodexSchemaSkillsExtraRootsSetParams
    ) -> CodexAppServerRequest<CodexSchemaSkillsExtraRootsSetResponse> {
        .required(method: .skillsExtraRootsSet, params: params)
    }
}
extension CodexRequest {
    public static func hooksList(
        _ params: CodexSchemaHooksListParams
    ) -> CodexAppServerRequest<CodexSchemaHooksListResponse> {
        .required(method: .hooksList, params: params)
    }
}
extension CodexRequest {
    public static func marketplaceAdd(
        _ params: CodexSchemaMarketplaceAddParams
    ) -> CodexAppServerRequest<CodexSchemaMarketplaceAddResponse> {
        .required(method: .marketplaceAdd, params: params)
    }
}
extension CodexRequest {
    public static func marketplaceRemove(
        _ params: CodexSchemaMarketplaceRemoveParams
    ) -> CodexAppServerRequest<CodexSchemaMarketplaceRemoveResponse> {
        .required(method: .marketplaceRemove, params: params)
    }
}
extension CodexRequest {
    public static func marketplaceUpgrade(
        _ params: CodexSchemaMarketplaceUpgradeParams
    ) -> CodexAppServerRequest<CodexSchemaMarketplaceUpgradeResponse> {
        .required(method: .marketplaceUpgrade, params: params)
    }
}
extension CodexRequest {
    public static func pluginList(
        _ params: CodexSchemaPluginListParams
    ) -> CodexAppServerRequest<CodexSchemaPluginListResponse> {
        .required(method: .pluginList, params: params)
    }
}
extension CodexRequest {
    public static func pluginSearch(
        _ params: CodexSchemaPluginSearchParams
    ) -> CodexAppServerRequest<CodexSchemaPluginSearchResponse> {
        .required(method: .pluginSearch, params: params)
    }
}
extension CodexRequest {
    public static func pluginInstalled(
        _ params: CodexSchemaPluginInstalledParams
    ) -> CodexAppServerRequest<CodexSchemaPluginInstalledResponse> {
        .required(method: .pluginInstalled, params: params)
    }
}
extension CodexRequest {
    public static func pluginRead(
        _ params: CodexSchemaPluginReadParams
    ) -> CodexAppServerRequest<CodexSchemaPluginReadResponse> {
        .required(method: .pluginRead, params: params)
    }
}
extension CodexRequest {
    public static func pluginSkillRead(
        _ params: CodexSchemaPluginSkillReadParams
    ) -> CodexAppServerRequest<CodexSchemaPluginSkillReadResponse> {
        .required(method: .pluginSkillRead, params: params)
    }
}
extension CodexRequest {
    public static func pluginShareSave(
        _ params: CodexSchemaPluginShareSaveParams
    ) -> CodexAppServerRequest<CodexSchemaPluginShareSaveResponse> {
        .required(method: .pluginShareSave, params: params)
    }
}
extension CodexRequest {
    public static func pluginShareUpdateTargets(
        _ params: CodexSchemaPluginShareUpdateTargetsParams
    ) -> CodexAppServerRequest<CodexSchemaPluginShareUpdateTargetsResponse> {
        .required(method: .pluginShareUpdateTargets, params: params)
    }
}
extension CodexRequest {
    public static func pluginShareList(
        _ params: CodexSchemaPluginShareListParams
    ) -> CodexAppServerRequest<CodexSchemaPluginShareListResponse> {
        .required(method: .pluginShareList, params: params)
    }
}
extension CodexRequest {
    public static func pluginShareCheckout(
        _ params: CodexSchemaPluginShareCheckoutParams
    ) -> CodexAppServerRequest<CodexSchemaPluginShareCheckoutResponse> {
        .required(method: .pluginShareCheckout, params: params)
    }
}
extension CodexRequest {
    public static func pluginShareDelete(
        _ params: CodexSchemaPluginShareDeleteParams
    ) -> CodexAppServerRequest<CodexSchemaPluginShareDeleteResponse> {
        .required(method: .pluginShareDelete, params: params)
    }
}
extension CodexRequest {
    public static func appRead(
        _ params: CodexSchemaAppsReadParams
    ) -> CodexAppServerRequest<CodexSchemaAppsReadResponse> {
        .required(method: .appRead, params: params)
    }
}
extension CodexRequest {
    public static func appList(
        _ params: CodexSchemaAppsListParams
    ) -> CodexAppServerRequest<CodexSchemaAppsListResponse> {
        .required(method: .appList, params: params)
    }
}
extension CodexRequest {
    public static func appInstalled(
        _ params: CodexSchemaAppsInstalledParams
    ) -> CodexAppServerRequest<CodexSchemaAppsInstalledResponse> {
        .required(method: .appInstalled, params: params)
    }
}
extension CodexRequest {
    public static func fsReadFile(
        _ params: CodexSchemaFSReadFileParams
    ) -> CodexAppServerRequest<CodexSchemaFSReadFileResponse> {
        .required(method: .fsReadFile, params: params)
    }
}
extension CodexRequest {
    public static func fsWriteFile(
        _ params: CodexSchemaFSWriteFileParams
    ) -> CodexAppServerRequest<CodexSchemaFSWriteFileResponse> {
        .required(method: .fsWriteFile, params: params)
    }
}
extension CodexRequest {
    public static func fsCreateDirectory(
        _ params: CodexSchemaFSCreateDirectoryParams
    ) -> CodexAppServerRequest<CodexSchemaFSCreateDirectoryResponse> {
        .required(method: .fsCreateDirectory, params: params)
    }
}
extension CodexRequest {
    public static func fsGetMetadata(
        _ params: CodexSchemaFSGetMetadataParams
    ) -> CodexAppServerRequest<CodexSchemaFSGetMetadataResponse> {
        .required(method: .fsGetMetadata, params: params)
    }
}
extension CodexRequest {
    public static func fsReadDirectory(
        _ params: CodexSchemaFSReadDirectoryParams
    ) -> CodexAppServerRequest<CodexSchemaFSReadDirectoryResponse> {
        .required(method: .fsReadDirectory, params: params)
    }
}
extension CodexRequest {
    public static func fsRemove(
        _ params: CodexSchemaFSRemoveParams
    ) -> CodexAppServerRequest<CodexSchemaFSRemoveResponse> {
        .required(method: .fsRemove, params: params)
    }
}
extension CodexRequest {
    public static func fsCopy(
        _ params: CodexSchemaFSCopyParams
    ) -> CodexAppServerRequest<CodexSchemaFSCopyResponse> {
        .required(method: .fsCopy, params: params)
    }
}
extension CodexRequest {
    public static func fsWatch(
        _ params: CodexSchemaFSWatchParams
    ) -> CodexAppServerRequest<CodexSchemaFSWatchResponse> {
        .required(method: .fsWatch, params: params)
    }
}
extension CodexRequest {
    public static func fsUnwatch(
        _ params: CodexSchemaFSUnwatchParams
    ) -> CodexAppServerRequest<CodexSchemaFSUnwatchResponse> {
        .required(method: .fsUnwatch, params: params)
    }
}
extension CodexRequest {
    public static func skillsConfigWrite(
        _ params: CodexSchemaSkillsConfigWriteParams
    ) -> CodexAppServerRequest<CodexSchemaSkillsConfigWriteResponse> {
        .required(method: .skillsConfigWrite, params: params)
    }
}
extension CodexRequest {
    public static func pluginInstall(
        _ params: CodexSchemaPluginInstallParams
    ) -> CodexAppServerRequest<CodexSchemaPluginInstallResponse> {
        .required(method: .pluginInstall, params: params)
    }
}
extension CodexRequest {
    public static func pluginUninstall(
        _ params: CodexSchemaPluginUninstallParams
    ) -> CodexAppServerRequest<CodexSchemaPluginUninstallResponse> {
        .required(method: .pluginUninstall, params: params)
    }
}
extension CodexRequest {
    static func turnStart(
        _ params: CodexSchemaTurnStartParams
    ) -> CodexAppServerRequest<CodexSchemaTurnStartResponse> {
        .required(method: .turnStart, params: params)
    }
}
extension CodexRequest {
    static func turnSteer(
        _ params: CodexSchemaTurnSteerParams
    ) -> CodexAppServerRequest<CodexSchemaTurnSteerResponse> {
        .required(method: .turnSteer, params: params)
    }
}
extension CodexRequest {
    static func turnInterrupt(
        _ params: CodexSchemaTurnInterruptParams
    ) -> CodexAppServerRequest<CodexSchemaTurnInterruptResponse> {
        .required(method: .turnInterrupt, params: params)
    }
}
extension CodexRequest {
    public static func threadRealtimeStart(
        _ params: CodexSchemaThreadRealtimeStartParams
    ) -> CodexAppServerRequest<CodexSchemaThreadRealtimeStartResponse> {
        .required(method: .threadRealtimeStart, params: params)
    }
}
extension CodexRequest {
    public static func threadRealtimeAppendAudio(
        _ params: CodexSchemaThreadRealtimeAppendAudioParams
    ) -> CodexAppServerRequest<CodexSchemaThreadRealtimeAppendAudioResponse> {
        .required(method: .threadRealtimeAppendAudio, params: params)
    }
}
extension CodexRequest {
    public static func threadRealtimeAppendText(
        _ params: CodexSchemaThreadRealtimeAppendTextParams
    ) -> CodexAppServerRequest<CodexSchemaThreadRealtimeAppendTextResponse> {
        .required(method: .threadRealtimeAppendText, params: params)
    }
}
extension CodexRequest {
    public static func threadRealtimeAppendSpeech(
        _ params: CodexSchemaThreadRealtimeAppendSpeechParams
    ) -> CodexAppServerRequest<CodexSchemaThreadRealtimeAppendSpeechResponse> {
        .required(method: .threadRealtimeAppendSpeech, params: params)
    }
}
extension CodexRequest {
    public static func threadRealtimeStop(
        _ params: CodexSchemaThreadRealtimeStopParams
    ) -> CodexAppServerRequest<CodexSchemaThreadRealtimeStopResponse> {
        .required(method: .threadRealtimeStop, params: params)
    }
}
extension CodexRequest {
    public static func threadRealtimeListVoices(
        _ params: CodexSchemaThreadRealtimeListVoicesParams
    ) -> CodexAppServerRequest<CodexSchemaThreadRealtimeListVoicesResponse> {
        .required(method: .threadRealtimeListVoices, params: params)
    }
}
extension CodexRequest {
    public static func reviewStart(
        _ params: CodexSchemaReviewStartParams
    ) -> CodexAppServerRequest<CodexSchemaReviewStartResponse> {
        .required(method: .reviewStart, params: params)
    }
}
extension CodexRequest {
    public static func modelList(
        _ params: CodexSchemaModelListParams
    ) -> CodexAppServerRequest<CodexSchemaModelListResponse> {
        .required(method: .modelList, params: params)
    }
}
extension CodexRequest {
    public static func modelProviderCapabilitiesRead(
        _ params: CodexSchemaModelProviderCapabilitiesReadParams
    ) -> CodexAppServerRequest<CodexSchemaModelProviderCapabilitiesReadResponse> {
        .required(method: .modelProviderCapabilitiesRead, params: params)
    }
}
extension CodexRequest {
    public static func experimentalFeatureList(
        _ params: CodexSchemaExperimentalFeatureListParams
    ) -> CodexAppServerRequest<CodexSchemaExperimentalFeatureListResponse> {
        .required(method: .experimentalFeatureList, params: params)
    }
}
extension CodexRequest {
    public static func permissionProfileList(
        _ params: CodexSchemaPermissionProfileListParams
    ) -> CodexAppServerRequest<CodexSchemaPermissionProfileListResponse> {
        .required(method: .permissionProfileList, params: params)
    }
}
extension CodexRequest {
    public static func experimentalFeatureEnablementSet(
        _ params: CodexSchemaExperimentalFeatureEnablementSetParams
    ) -> CodexAppServerRequest<CodexSchemaExperimentalFeatureEnablementSetResponse> {
        .required(method: .experimentalFeatureEnablementSet, params: params)
    }
}
extension CodexRequest {
    public static func remoteControlEnable(
        _ params: CodexNullableRequestParameters<
            CodexSchemaRemoteControlEnableParams
        > = .omitted
    ) -> CodexAppServerRequest<CodexSchemaRemoteControlEnableResponse> {
        .nullable(method: .remoteControlEnable, params: params)
    }
}
extension CodexRequest {
    public static func remoteControlDisable(
        _ params: CodexNullableRequestParameters<
            CodexSchemaRemoteControlDisableParams
        > = .omitted
    ) -> CodexAppServerRequest<CodexSchemaRemoteControlDisableResponse> {
        .nullable(method: .remoteControlDisable, params: params)
    }
}
extension CodexRequest {
    public static func remoteControlStatusRead() -> CodexAppServerRequest<CodexSchemaRemoteControlStatusReadResponse> {
        .omitted(method: .remoteControlStatusRead)
    }
}
extension CodexRequest {
    public static func remoteControlPairingStart(
        _ params: CodexSchemaRemoteControlPairingStartParams
    ) -> CodexAppServerRequest<CodexSchemaRemoteControlPairingStartResponse> {
        .required(method: .remoteControlPairingStart, params: params)
    }
}
extension CodexRequest {
    public static func remoteControlPairingStatus(
        _ params: CodexSchemaRemoteControlPairingStatusParams
    ) -> CodexAppServerRequest<CodexSchemaRemoteControlPairingStatusResponse> {
        .required(method: .remoteControlPairingStatus, params: params)
    }
}
extension CodexRequest {
    public static func remoteControlClientList(
        _ params: CodexSchemaRemoteControlClientsListParams
    ) -> CodexAppServerRequest<CodexSchemaRemoteControlClientsListResponse> {
        .required(method: .remoteControlClientList, params: params)
    }
}
extension CodexRequest {
    public static func remoteControlClientRevoke(
        _ params: CodexSchemaRemoteControlClientsRevokeParams
    ) -> CodexAppServerRequest<CodexSchemaRemoteControlClientsRevokeResponse> {
        .required(method: .remoteControlClientRevoke, params: params)
    }
}
extension CodexRequest {
    public static func collaborationModeList(
        _ params: CodexSchemaCollaborationModeListParams
    ) -> CodexAppServerRequest<CodexSchemaCollaborationModeListResponse> {
        .required(method: .collaborationModeList, params: params)
    }
}
extension CodexRequest {
    public static func mockExperimentalMethod(
        _ params: CodexSchemaMockExperimentalMethodParams
    ) -> CodexAppServerRequest<CodexSchemaMockExperimentalMethodResponse> {
        .required(method: .mockExperimentalMethod, params: params)
    }
}
extension CodexRequest {
    public static func environmentAdd(
        _ params: CodexSchemaEnvironmentAddParams
    ) -> CodexAppServerRequest<CodexSchemaEnvironmentAddResponse> {
        .required(method: .environmentAdd, params: params)
    }
}
extension CodexRequest {
    public static func environmentInfo(
        _ params: CodexSchemaEnvironmentInfoParams
    ) -> CodexAppServerRequest<CodexSchemaEnvironmentInfoResponse> {
        .required(method: .environmentInfo, params: params)
    }
}
extension CodexRequest {
    public static func environmentStatus(
        _ params: CodexSchemaEnvironmentStatusParams
    ) -> CodexAppServerRequest<CodexSchemaEnvironmentStatusResponse> {
        .required(method: .environmentStatus, params: params)
    }
}
extension CodexRequest {
    public static func mcpServerOAuthLogin(
        _ params: CodexSchemaMCPServerOAuthLoginParams
    ) -> CodexAppServerRequest<CodexSchemaMCPServerOAuthLoginResponse> {
        .required(method: .mcpServerOAuthLogin, params: params)
    }
}
extension CodexRequest {
    public static func configMCPServerReload() -> CodexAppServerRequest<CodexSchemaMCPServerRefreshResponse> {
        .omitted(method: .configMCPServerReload)
    }
}
extension CodexRequest {
    public static func mcpServerStatusList(
        _ params: CodexSchemaListMCPServerStatusParams
    ) -> CodexAppServerRequest<CodexSchemaListMCPServerStatusResponse> {
        .required(method: .mcpServerStatusList, params: params)
    }
}
extension CodexRequest {
    public static func mcpServerResourceRead(
        _ params: CodexSchemaMCPResourceReadParams
    ) -> CodexAppServerRequest<CodexSchemaMCPResourceReadResponse> {
        .required(method: .mcpServerResourceRead, params: params)
    }
}
extension CodexRequest {
    public static func mcpServerToolCall(
        _ params: CodexSchemaMCPServerToolCallParams
    ) -> CodexAppServerRequest<CodexSchemaMCPServerToolCallResponse> {
        .required(method: .mcpServerToolCall, params: params)
    }
}
extension CodexRequest {
    public static func windowsSandboxSetupStart(
        _ params: CodexSchemaWindowsSandboxSetupStartParams
    ) -> CodexAppServerRequest<CodexSchemaWindowsSandboxSetupStartResponse> {
        .required(method: .windowsSandboxSetupStart, params: params)
    }
}
extension CodexRequest {
    public static func windowsSandboxReadiness() -> CodexAppServerRequest<CodexSchemaWindowsSandboxReadinessResponse> {
        .omitted(method: .windowsSandboxReadiness)
    }
}
extension CodexRequest {
    static func accountLoginStart(
        _ params: CodexSchemaLoginAccountParams
    ) -> CodexAppServerRequest<CodexSchemaLoginAccountResponse> {
        .required(method: .accountLoginStart, params: params)
    }
}
extension CodexRequest {
    static func accountLoginCancel(
        _ params: CodexSchemaCancelLoginAccountParams
    ) -> CodexAppServerRequest<CodexSchemaCancelLoginAccountResponse> {
        .required(method: .accountLoginCancel, params: params)
    }
}
extension CodexRequest {
    public static func accountLogout() -> CodexAppServerRequest<CodexSchemaLogoutAccountResponse> {
        .omitted(method: .accountLogout)
    }
}
extension CodexRequest {
    public static func accountRateLimitsRead() -> CodexAppServerRequest<CodexSchemaGetAccountRateLimitsResponse> {
        .omitted(method: .accountRateLimitsRead)
    }
}
extension CodexRequest {
    public static func accountRateLimitResetCreditConsume(
        _ params: CodexSchemaConsumeAccountRateLimitResetCreditParams
    ) -> CodexAppServerRequest<CodexSchemaConsumeAccountRateLimitResetCreditResponse> {
        .required(method: .accountRateLimitResetCreditConsume, params: params)
    }
}
extension CodexRequest {
    public static func accountUsageRead(
        _ params: CodexNullableRequestParameters<
            CodexSchemaGetAccountTokenUsageParams
        > = .omitted
    ) -> CodexAppServerRequest<CodexSchemaGetAccountTokenUsageResponse> {
        .nullable(method: .accountUsageRead, params: params)
    }
}
extension CodexRequest {
    public static func accountWorkspaceMessagesRead() -> CodexAppServerRequest<CodexSchemaGetWorkspaceMessagesResponse> {
        .omitted(method: .accountWorkspaceMessagesRead)
    }
}
extension CodexRequest {
    public static func accountSendAddCreditsNudgeEmail(
        _ params: CodexSchemaSendAddCreditsNudgeEmailParams
    ) -> CodexAppServerRequest<CodexSchemaSendAddCreditsNudgeEmailResponse> {
        .required(method: .accountSendAddCreditsNudgeEmail, params: params)
    }
}
extension CodexRequest {
    public static func feedbackUpload(
        _ params: CodexSchemaFeedbackUploadParams
    ) -> CodexAppServerRequest<CodexSchemaFeedbackUploadResponse> {
        .required(method: .feedbackUpload, params: params)
    }
}
extension CodexRequest {
    public static func commandExec(
        _ params: CodexSchemaCommandExecParams
    ) -> CodexAppServerRequest<CodexSchemaCommandExecResponse> {
        .required(method: .commandExec, params: params)
    }
}
extension CodexRequest {
    public static func commandExecWrite(
        _ params: CodexSchemaCommandExecWriteParams
    ) -> CodexAppServerRequest<CodexSchemaCommandExecWriteResponse> {
        .required(method: .commandExecWrite, params: params)
    }
}
extension CodexRequest {
    public static func commandExecTerminate(
        _ params: CodexSchemaCommandExecTerminateParams
    ) -> CodexAppServerRequest<CodexSchemaCommandExecTerminateResponse> {
        .required(method: .commandExecTerminate, params: params)
    }
}
extension CodexRequest {
    public static func commandExecResize(
        _ params: CodexSchemaCommandExecResizeParams
    ) -> CodexAppServerRequest<CodexSchemaCommandExecResizeResponse> {
        .required(method: .commandExecResize, params: params)
    }
}
extension CodexRequest {
    public static func processSpawn(
        _ params: CodexSchemaProcessSpawnParams
    ) -> CodexAppServerRequest<CodexSchemaProcessSpawnResponse> {
        .required(method: .processSpawn, params: params)
    }
}
extension CodexRequest {
    public static func processWriteStdin(
        _ params: CodexSchemaProcessWriteStdinParams
    ) -> CodexAppServerRequest<CodexSchemaProcessWriteStdinResponse> {
        .required(method: .processWriteStdin, params: params)
    }
}
extension CodexRequest {
    public static func processKill(
        _ params: CodexSchemaProcessKillParams
    ) -> CodexAppServerRequest<CodexSchemaProcessKillResponse> {
        .required(method: .processKill, params: params)
    }
}
extension CodexRequest {
    public static func processResizePTY(
        _ params: CodexSchemaProcessResizePTYParams
    ) -> CodexAppServerRequest<CodexSchemaProcessResizePTYResponse> {
        .required(method: .processResizePTY, params: params)
    }
}
extension CodexRequest {
    public static func configRead(
        _ params: CodexSchemaConfigReadParams
    ) -> CodexAppServerRequest<CodexSchemaConfigReadResponse> {
        .required(method: .configRead, params: params)
    }
}
extension CodexRequest {
    public static func externalAgentConfigDetect(
        _ params: CodexSchemaExternalAgentConfigDetectParams
    ) -> CodexAppServerRequest<CodexSchemaExternalAgentConfigDetectResponse> {
        .required(method: .externalAgentConfigDetect, params: params)
    }
}
extension CodexRequest {
    public static func externalAgentConfigImport(
        _ params: CodexSchemaExternalAgentConfigImportParams
    ) -> CodexAppServerRequest<CodexSchemaExternalAgentConfigImportResponse> {
        .required(method: .externalAgentConfigImport, params: params)
    }
}
extension CodexRequest {
    public static func externalAgentConfigImportRecordHistory(
        _ params: CodexSchemaExternalAgentConfigImportHistoryRecordParams
    ) -> CodexAppServerRequest<CodexSchemaExternalAgentConfigImportHistoryRecordResponse> {
        .required(method: .externalAgentConfigImportRecordHistory, params: params)
    }
}
extension CodexRequest {
    public static func externalAgentConfigImportReadHistories() -> CodexAppServerRequest<CodexSchemaExternalAgentConfigImportHistoriesReadResponse> {
        .omitted(method: .externalAgentConfigImportReadHistories)
    }
}
extension CodexRequest {
    public static func configValueWrite(
        _ params: CodexSchemaConfigValueWriteParams
    ) -> CodexAppServerRequest<CodexSchemaConfigWriteResponse> {
        .required(method: .configValueWrite, params: params)
    }
}
extension CodexRequest {
    public static func configBatchWrite(
        _ params: CodexSchemaConfigBatchWriteParams
    ) -> CodexAppServerRequest<CodexSchemaConfigWriteResponse> {
        .required(method: .configBatchWrite, params: params)
    }
}
extension CodexRequest {
    public static func configRequirementsRead() -> CodexAppServerRequest<CodexSchemaConfigRequirementsReadResponse> {
        .omitted(method: .configRequirementsRead)
    }
}
extension CodexRequest {
    public static func accountRead(
        _ params: CodexSchemaGetAccountParams
    ) -> CodexAppServerRequest<CodexSchemaGetAccountResponse> {
        .required(method: .accountRead, params: params)
    }
}
extension CodexRequest {
    public static func fuzzyFileSearch(
        _ params: CodexSchemaFuzzyFileSearchParams
    ) -> CodexAppServerRequest<FuzzyFileSearchResponse> {
        .required(method: .fuzzyFileSearch, params: params)
    }
}
extension CodexRequest {
    public static func fuzzyFileSearchSessionStart(
        _ params: CodexSchemaFuzzyFileSearchSessionStartParams
    ) -> CodexAppServerRequest<EmptyResponse> {
        .required(method: .fuzzyFileSearchSessionStart, params: params)
    }
}
extension CodexRequest {
    public static func fuzzyFileSearchSessionUpdate(
        _ params: CodexSchemaFuzzyFileSearchSessionUpdateParams
    ) -> CodexAppServerRequest<EmptyResponse> {
        .required(method: .fuzzyFileSearchSessionUpdate, params: params)
    }
}
extension CodexRequest {
    public static func fuzzyFileSearchSessionStop(
        _ params: CodexSchemaFuzzyFileSearchSessionStopParams
    ) -> CodexAppServerRequest<EmptyResponse> {
        .required(method: .fuzzyFileSearchSessionStop, params: params)
    }
}
public extension CodexRequest {
    static let generatedMethodCount = 140
    static let supportedMethods: Set<CodexAppServerClientMethod> = [
        .serverDiagnostics,
        .threadStart,
        .threadResume,
        .threadFork,
        .threadArchive,
        .threadDelete,
        .threadUnsubscribe,
        .threadIncrementElicitation,
        .threadDecrementElicitation,
        .threadNameSet,
        .threadGoalSet,
        .threadGoalGet,
        .threadGoalClear,
        .threadQueueAdd,
        .threadQueueList,
        .threadQueueUpdate,
        .threadQueueDelete,
        .threadQueueReorder,
        .threadQueueStart,
        .threadMetadataUpdate,
        .threadSectionMove,
        .threadSettingsUpdate,
        .threadMemoryModeSet,
        .memoryReset,
        .threadUnarchive,
        .threadCompactStart,
        .threadShellCommand,
        .threadApproveGuardianDeniedAction,
        .threadBackgroundTerminalsClean,
        .threadBackgroundTerminalsList,
        .threadBackgroundTerminalsTerminate,
        .threadRollback,
        .threadRevert,
        .threadList,
        .threadSectionList,
        .threadSectionCreate,
        .threadSectionUpdate,
        .threadSectionDelete,
        .threadSearch,
        .threadSearchOccurrences,
        .threadLoadedList,
        .threadRead,
        .threadTurnsList,
        .threadItemsList,
        .threadInjectItems,
        .skillsList,
        .skillsExtraRootsSet,
        .hooksList,
        .marketplaceAdd,
        .marketplaceRemove,
        .marketplaceUpgrade,
        .pluginList,
        .pluginSearch,
        .pluginInstalled,
        .pluginRead,
        .pluginSkillRead,
        .pluginShareSave,
        .pluginShareUpdateTargets,
        .pluginShareList,
        .pluginShareCheckout,
        .pluginShareDelete,
        .appRead,
        .appList,
        .appInstalled,
        .fsReadFile,
        .fsWriteFile,
        .fsCreateDirectory,
        .fsGetMetadata,
        .fsReadDirectory,
        .fsRemove,
        .fsCopy,
        .fsWatch,
        .fsUnwatch,
        .skillsConfigWrite,
        .pluginInstall,
        .pluginUninstall,
        .turnStart,
        .turnSteer,
        .turnInterrupt,
        .threadRealtimeStart,
        .threadRealtimeAppendAudio,
        .threadRealtimeAppendText,
        .threadRealtimeAppendSpeech,
        .threadRealtimeStop,
        .threadRealtimeListVoices,
        .reviewStart,
        .modelList,
        .modelProviderCapabilitiesRead,
        .experimentalFeatureList,
        .permissionProfileList,
        .experimentalFeatureEnablementSet,
        .remoteControlEnable,
        .remoteControlDisable,
        .remoteControlStatusRead,
        .remoteControlPairingStart,
        .remoteControlPairingStatus,
        .remoteControlClientList,
        .remoteControlClientRevoke,
        .collaborationModeList,
        .mockExperimentalMethod,
        .environmentAdd,
        .environmentInfo,
        .environmentStatus,
        .mcpServerOAuthLogin,
        .configMCPServerReload,
        .mcpServerStatusList,
        .mcpServerResourceRead,
        .mcpServerToolCall,
        .windowsSandboxSetupStart,
        .windowsSandboxReadiness,
        .accountLoginStart,
        .accountLoginCancel,
        .accountLogout,
        .accountRateLimitsRead,
        .accountRateLimitResetCreditConsume,
        .accountUsageRead,
        .accountWorkspaceMessagesRead,
        .accountSendAddCreditsNudgeEmail,
        .feedbackUpload,
        .commandExec,
        .commandExecWrite,
        .commandExecTerminate,
        .commandExecResize,
        .processSpawn,
        .processWriteStdin,
        .processKill,
        .processResizePTY,
        .configRead,
        .externalAgentConfigDetect,
        .externalAgentConfigImport,
        .externalAgentConfigImportRecordHistory,
        .externalAgentConfigImportReadHistories,
        .configValueWrite,
        .configBatchWrite,
        .configRequirementsRead,
        .accountRead,
        .fuzzyFileSearch,
        .fuzzyFileSearchSessionStart,
        .fuzzyFileSearchSessionUpdate,
        .fuzzyFileSearchSessionStop,
    ]
    static let omittedParameterMethods: Set<CodexAppServerClientMethod> = [
        .memoryReset,
        .remoteControlStatusRead,
        .configMCPServerReload,
        .windowsSandboxReadiness,
        .accountLogout,
        .accountRateLimitsRead,
        .accountWorkspaceMessagesRead,
        .externalAgentConfigImportReadHistories,
        .configRequirementsRead,
    ]
    static let nullableParameterMethods: Set<CodexAppServerClientMethod> = [
        .remoteControlEnable,
        .remoteControlDisable,
        .accountUsageRead,
    ]
    static let specializedMethods: Set<CodexAppServerClientMethod> = [
        .threadStart,
        .threadResume,
        .threadFork,
        .threadUnsubscribe,
        .turnStart,
        .turnSteer,
        .turnInterrupt,
        .accountLoginStart,
        .accountLoginCancel,
    ]
}
public extension CodexSession {
    /// Performs one typed request through the session's ordered JSON-RPC seam.
    /// Stateful responses are committed to canonical state before this method
    /// returns; callers can query the response's entities immediately.
    func perform<Response: Decodable & Sendable>(
        _ request: CodexAppServerRequest<Response>
    ) async throws -> Response {
        let result = try await perform(
            method: request.method,
            params: try request.encodeParameters()
        )
        return try result.decode(Response.self)
    }
}
