#!/usr/bin/env python3
"""Generate Swift model types from Codex app-server JSON schemas.

String-enum schemas become Swift enums, plain object schemas become Codable
structs, and anything the generator cannot faithfully express (tagged unions,
recursive types, exotic compositions) falls back to a raw JSON wrapper
typealias so the full definition inventory stays addressable.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from swift_naming import swift_member_name, swift_type_suffix


HEADER = """// Generated by Tools/generate_app_server_schema_types.py. Do not edit by hand.
// Regenerate with Tools/regenerate.sh; verify with Tools/check_drift.sh.
import Foundation

/// Raw JSON wrapper used for schema definitions the generator cannot express
/// as a concrete Swift type (tagged unions, recursive types, etc.).
public struct CodexAppServerSchemaValue: Codable, Sendable, Equatable {
    public var rawValue: CodexJSONValue

    public init(_ rawValue: CodexJSONValue = .dictionary([:])) {
        self.rawValue = rawValue
    }

    public init(from decoder: Decoder) throws {
        self.rawValue = try CodexJSONValue(from: decoder)
    }

    public func encode(to encoder: Encoder) throws {
        try rawValue.encode(to: encoder)
    }
}

public struct CodexAppServerSchemaDefinition: Sendable, Equatable {
    public let name: String
    public let typeName: String
}

public struct CodexAppServerMethodSchemaDefinition: Sendable, Equatable {
    public let method: String
    public let definitionName: String
    public let typeName: String
}

"""

def ref_name(value: object) -> str | None:
    if isinstance(value, str) and value.startswith("#/definitions/"):
        return value.removeprefix("#/definitions/")
    return None


def string_enum_values(schema: dict) -> list[str] | None:
    """Return enum raw values when the schema is a plain string enum."""
    if schema.get("type") == "string":
        values = schema.get("enum")
        if isinstance(values, list) and values and all(isinstance(v, str) for v in values):
            return values
    arms = schema.get("oneOf")
    if isinstance(arms, list) and arms:
        values = []
        for arm in arms:
            if not isinstance(arm, dict):
                return None
            arm_values = arm.get("enum")
            if arm.get("type") == "string" and isinstance(arm_values, list) and len(arm_values) == 1 and isinstance(arm_values[0], str):
                values.append(arm_values[0])
            else:
                return None
        return values
    return None


def is_plain_object(schema: dict) -> bool:
    if schema.get("type") != "object":
        return False
    if any(key in schema for key in ("oneOf", "anyOf", "allOf", "enum")):
        return False
    return isinstance(schema.get("properties"), dict)


class FieldTypeResolver:
    def __init__(self, type_names: dict[str, str]):
        self.type_names = type_names
        self.refs: set[str] = set()

    def resolve(self, schema: object, optional: bool) -> str:
        base = self._resolve(schema)
        if optional and not base.endswith("?"):
            base += "?"
        return base

    def _resolve(self, schema: object) -> str:
        if not isinstance(schema, dict):
            return "CodexJSONValue"

        name = ref_name(schema.get("$ref"))
        if name is not None:
            if name in self.type_names:
                self.refs.add(name)
                return self.type_names[name]
            return "CodexJSONValue"

        all_of = schema.get("allOf")
        if isinstance(all_of, list) and len(all_of) == 1:
            return self._resolve(all_of[0])

        for union_key in ("anyOf", "oneOf"):
            arms = schema.get(union_key)
            if isinstance(arms, list):
                non_null = [arm for arm in arms if isinstance(arm, dict) and arm.get("type") != "null"]
                if len(arms) == 2 and len(non_null) == 1:
                    base = self._resolve(non_null[0])
                    return base if base.endswith("?") else base + "?"
                return "CodexJSONValue"

        type_value = schema.get("type")
        if isinstance(type_value, list):
            non_null = [t for t in type_value if t != "null"]
            if len(non_null) == 1:
                narrowed = dict(schema)
                narrowed["type"] = non_null[0]
                base = self._resolve(narrowed)
                return base if base.endswith("?") else base + "?"
            return "CodexJSONValue"

        if type_value == "string":
            return "String"
        if type_value == "integer":
            return "Int"
        if type_value == "number":
            return "Double"
        if type_value == "boolean":
            return "Bool"
        if type_value == "array":
            return "[" + self._resolve(schema.get("items", {})) + "]"
        if type_value == "object":
            properties = schema.get("properties")
            additional = schema.get("additionalProperties")
            if not properties and isinstance(additional, dict):
                return "[String: " + self._resolve(additional) + "]"
            return "CodexJSONValue"
        return "CodexJSONValue"


def emit_enum(type_name: str, values: list[str]) -> str:
    lines = [f"public enum {type_name}: String, Codable, Sendable, Equatable, CaseIterable {{"]
    used: dict[str, int] = {}
    for value in values:
        case_name = swift_member_name(value)
        count = used.get(case_name, 0)
        used[case_name] = count + 1
        if count:
            case_name = f"{case_name}{count + 1}"
        lines.append(f"    case {case_name} = {json.dumps(value)}")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def emit_struct(type_name: str, schema: dict, type_names: dict[str, str]) -> tuple[str, set[str]]:
    properties: dict = schema.get("properties", {})
    required = set(schema.get("required", []) or [])
    resolver = FieldTypeResolver(type_names)

    fields: list[tuple[str, str, str, bool]] = []  # (property, json key, type, optional)
    used: dict[str, int] = {}
    for key in sorted(properties):
        prop_name = swift_member_name(key)
        count = used.get(prop_name, 0)
        used[prop_name] = count + 1
        if count:
            prop_name = f"{prop_name}{count + 1}"
        optional = key not in required
        swift_type = resolver.resolve(properties[key], optional)
        fields.append((prop_name, key, swift_type, optional))

    lines = [f"public struct {type_name}: Codable, Sendable, Equatable {{"]
    for prop_name, _, swift_type, _ in fields:
        lines.append(f"    public var {prop_name}: {swift_type}")

    needs_keys = any(prop.strip("`") != key for prop, key, _, _ in fields)
    if needs_keys:
        lines.append("")
        lines.append("    enum CodingKeys: String, CodingKey {")
        for prop_name, key, _, _ in fields:
            bare = prop_name.strip("`")
            if bare != key:
                lines.append(f"        case {prop_name} = {json.dumps(key)}")
            else:
                lines.append(f"        case {prop_name}")
        lines.append("    }")

    lines.append("")
    if fields:
        params = ", ".join(
            f"{prop}: {swift_type}{' = nil' if swift_type.endswith('?') else ''}"
            for prop, _, swift_type, _ in fields
        )
        lines.append(f"    public init({params}) {{")
        for prop_name, _, _, _ in fields:
            bare = prop_name.strip("`")
            lines.append(f"        self.{bare} = {prop_name}")
        lines.append("    }")
    else:
        lines.append("    public init() {}")
    lines.append("}")
    lines.append("")
    return "\n".join(lines), resolver.refs


def load_method_param_refs(path: Path, type_names: dict[str, str]) -> list[tuple[str, str, str]]:
    data = json.loads(path.read_text())
    rows: list[tuple[str, str, str]] = []
    for arm in data.get("oneOf", []):
        properties = arm.get("properties", {})
        enum_values = properties.get("method", {}).get("enum", [])
        ref = properties.get("params", {}).get("$ref")
        if not enum_values or not isinstance(ref, str) or not ref.startswith("#/definitions/"):
            continue
        definition_name = ref.removeprefix("#/definitions/")
        type_name = type_names.get(definition_name, "")
        rows.append((enum_values[0], definition_name, type_name))
    return rows


def detect_cycles(struct_refs: dict[str, set[str]]) -> set[str]:
    """Return struct definitions that participate in a reference cycle.

    Swift structs cannot recursively contain themselves by value, so any
    definition in a cycle is demoted to the raw fallback typealias.
    """
    cyclic: set[str] = set()
    graph = {name: {ref for ref in refs if ref in struct_refs} for name, refs in struct_refs.items()}

    state: dict[str, int] = {}  # 0 visiting, 1 done
    stack: list[str] = []

    def visit(node: str) -> None:
        state[node] = 0
        stack.append(node)
        for neighbor in graph.get(node, ()):  # noqa: B007
            if neighbor not in state:
                visit(neighbor)
            elif state[neighbor] == 0:
                # Found a back edge: everything from neighbor on the stack is cyclic.
                idx = stack.index(neighbor)
                cyclic.update(stack[idx:])
        stack.pop()
        state[node] = 1

    for name in graph:
        if name not in state:
            visit(name)
    return cyclic


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--schema-dir", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    bundle = json.loads((args.schema_dir / "codex_app_server_protocol.v2.schemas.json").read_text())
    definitions = bundle.get("definitions", {})
    if not isinstance(definitions, dict):
        raise ValueError("schema bundle definitions must be an object")

    rows: list[tuple[str, str]] = []
    used: dict[str, int] = {}
    # The codex binary emits definitions in nondeterministic (hash map) order;
    # sort by name so regeneration is reproducible and diffs stay meaningful.
    for name in sorted(definitions):
        base = "CodexSchema" + swift_type_suffix(name)
        count = used.get(base, 0)
        used[base] = count + 1
        type_name = base if count == 0 else f"{base}{count + 1}"
        rows.append((name, type_name))

    type_names = dict(rows)

    # Classify definitions.
    enums: dict[str, list[str]] = {}
    structs: dict[str, dict] = {}
    for name in type_names:
        schema = definitions[name]
        if not isinstance(schema, dict):
            continue
        values = string_enum_values(schema)
        if values is not None:
            enums[name] = values
            continue
        if is_plain_object(schema):
            structs[name] = schema

    # First pass: collect struct reference graphs for cycle demotion.
    struct_refs: dict[str, set[str]] = {}
    for name, schema in structs.items():
        _, refs = emit_struct(type_names[name], schema, type_names)
        struct_refs[name] = refs
    for name in detect_cycles(struct_refs):
        structs.pop(name, None)

    client_params = load_method_param_refs(args.schema_dir / "ClientRequest.json", type_names)
    notification_payloads = load_method_param_refs(args.schema_dir / "ServerNotification.json", type_names)
    server_request_params = load_method_param_refs(args.schema_dir / "ServerRequest.json", type_names)

    v2_files = sorted(path.name for path in (args.schema_dir / "v2").glob("*.json"))

    enum_count = 0
    struct_count = 0
    alias_count = 0

    output = HEADER
    for name, type_name in rows:
        if name in enums:
            output += emit_enum(type_name, enums[name])
            enum_count += 1
        elif name in structs:
            body, _ = emit_struct(type_name, structs[name], type_names)
            output += body
            struct_count += 1
        else:
            output += f"public typealias {type_name} = CodexAppServerSchemaValue\n"
            alias_count += 1

    output += "\npublic enum CodexAppServerSchemaInventory {\n"
    output += f"    public static let definitionCount = {len(rows)}\n"
    output += f"    public static let generatedEnumCount = {enum_count}\n"
    output += f"    public static let generatedStructCount = {struct_count}\n"
    output += f"    public static let rawAliasCount = {alias_count}\n"
    output += f"    public static let v2SchemaFileCount = {len(v2_files)}\n"
    output += "    public static let definitions: [CodexAppServerSchemaDefinition] = [\n"
    for name, type_name in rows:
        output += f"        CodexAppServerSchemaDefinition(name: {json.dumps(name)}, typeName: {json.dumps(type_name)}),\n"
    output += "    ]\n"
    output += f"    public static let clientRequestParamCount = {len(client_params)}\n"
    output += f"    public static let notificationPayloadCount = {len(notification_payloads)}\n"
    output += f"    public static let serverRequestParamCount = {len(server_request_params)}\n"
    output += "    public static let clientRequestParams: [CodexAppServerMethodSchemaDefinition] = [\n"
    for method, definition_name, type_name in client_params:
        output += f"        CodexAppServerMethodSchemaDefinition(method: {json.dumps(method)}, definitionName: {json.dumps(definition_name)}, typeName: {json.dumps(type_name)}),\n"
    output += "    ]\n"
    output += "    public static let notificationPayloads: [CodexAppServerMethodSchemaDefinition] = [\n"
    for method, definition_name, type_name in notification_payloads:
        output += f"        CodexAppServerMethodSchemaDefinition(method: {json.dumps(method)}, definitionName: {json.dumps(definition_name)}, typeName: {json.dumps(type_name)}),\n"
    output += "    ]\n"
    output += "    public static let serverRequestParams: [CodexAppServerMethodSchemaDefinition] = [\n"
    for method, definition_name, type_name in server_request_params:
        output += f"        CodexAppServerMethodSchemaDefinition(method: {json.dumps(method)}, definitionName: {json.dumps(definition_name)}, typeName: {json.dumps(type_name)}),\n"
    output += "    ]\n"
    output += "    public static let clientRequestParamByMethod: [String: CodexAppServerMethodSchemaDefinition] = Dictionary(uniqueKeysWithValues: clientRequestParams.map { ($0.method, $0) })\n"
    output += "    public static let notificationPayloadByMethod: [String: CodexAppServerMethodSchemaDefinition] = Dictionary(uniqueKeysWithValues: notificationPayloads.map { ($0.method, $0) })\n"
    output += "    public static let serverRequestParamByMethod: [String: CodexAppServerMethodSchemaDefinition] = Dictionary(uniqueKeysWithValues: serverRequestParams.map { ($0.method, $0) })\n"
    output += "    public static let v2SchemaFiles: [String] = [\n"
    for file_name in v2_files:
        output += f"        {json.dumps(file_name)},\n"
    output += "    ]\n"
    output += "}\n"
    output += "\npublic extension CodexAppServerNotificationMethod {\n"
    output += "    var schemaDefinition: CodexAppServerMethodSchemaDefinition? {\n"
    output += "        CodexAppServerSchemaInventory.notificationPayloadByMethod[rawValue]\n"
    output += "    }\n"
    output += "}\n"
    output += "\npublic extension CodexAppServerClientMethod {\n"
    output += "    var paramsSchemaDefinition: CodexAppServerMethodSchemaDefinition? {\n"
    output += "        CodexAppServerSchemaInventory.clientRequestParamByMethod[rawValue]\n"
    output += "    }\n"
    output += "}\n"
    output += "\npublic extension CodexAppServerServerRequestMethod {\n"
    output += "    var paramsSchemaDefinition: CodexAppServerMethodSchemaDefinition? {\n"
    output += "        CodexAppServerSchemaInventory.serverRequestParamByMethod[rawValue]\n"
    output += "    }\n"
    output += "}\n"

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(output)
    print(f"schema types: {enum_count} enums, {struct_count} structs, {alias_count} raw aliases")


if __name__ == "__main__":
    main()
