#!/usr/bin/env python3
"""Generate the typed CodexSession request surface from app-server schemas.

The app-server JSON schema declares the exact request method and parameter
shape, but does not carry a request-to-response map. Response definitions
normally share the parameter stem; the small set of protocol naming exceptions
is kept explicit and validated against the same schema bundle.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path

from generate_app_server_methods import swift_case
from swift_naming import swift_type_suffix


HEADER = """// Generated by Tools/generate_app_server_requests.py. Do not edit by hand.
// Regenerate with Tools/regenerate.sh; verify with Tools/check_drift.sh.
import Foundation

/// The three wire representations allowed by nullable app-server parameters.
///
/// This is intentionally not `Optional`: an omitted JSON-RPC `params` member,
/// an explicit JSON null, and an encoded value are three distinct protocol
/// states while the app-server API is experimental.
public enum CodexNullableRequestParameters<Value: Encodable & Sendable>: Sendable {
    case omitted
    case null
    case value(Value)
}

/// A sealed compile-time pairing of one app-server method and response.
///
/// Its initializer is module-internal: external callers can only obtain a
/// value from generated `CodexRequest` factories, so they cannot forge a false
/// method/response pairing or bypass specialized lifecycle commands.
public struct CodexAppServerRequest<Response: Decodable & Sendable>: Sendable {
    public let method: CodexAppServerClientMethod
    private let parameterEncoder: @Sendable () throws -> CodexJSONValue?

    private init(
        method: CodexAppServerClientMethod,
        parameterEncoder: @escaping @Sendable () throws -> CodexJSONValue?
    ) {
        self.method = method
        self.parameterEncoder = parameterEncoder
    }

    fileprivate static func required<Parameters: Encodable & Sendable>(
        method: CodexAppServerClientMethod,
        params: Parameters
    ) -> Self {
        Self(method: method) { try CodexJSONValue(encoding: params) }
    }

    fileprivate static func omitted(method: CodexAppServerClientMethod) -> Self {
        Self(method: method) { nil }
    }

    fileprivate static func nullable<Parameters: Encodable & Sendable>(
        method: CodexAppServerClientMethod,
        params: CodexNullableRequestParameters<Parameters>
    ) -> Self {
        Self(method: method) {
            switch params {
            case .omitted: nil
            case .null: .null
            case .value(let value): try CodexJSONValue(encoding: value)
            }
        }
    }

    func encodeParameters() throws -> CodexJSONValue? {
        try parameterEncoder()
    }
}

/// Namespace for generated, protocol-native app-server request factories.
public enum CodexRequest {}

"""


# Methods whose response definition does not share the generated parameter stem.
RESPONSE_DEFINITION_OVERRIDES = {
    "memory/reset": "MemoryResetResponse",
    "remoteControl/status/read": "RemoteControlStatusReadResponse",
    "config/mcpServer/reload": "McpServerRefreshResponse",
    "windowsSandbox/readiness": "WindowsSandboxReadinessResponse",
    "account/logout": "LogoutAccountResponse",
    "account/rateLimits/read": "GetAccountRateLimitsResponse",
    "account/usage/read": "GetAccountTokenUsageResponse",
    "account/workspaceMessages/read": "GetWorkspaceMessagesResponse",
    "externalAgentConfig/import/readHistories": "ExternalAgentConfigImportHistoriesReadResponse",
    "configRequirements/read": "ConfigRequirementsReadResponse",
    "config/value/write": "ConfigWriteResponse",
    "config/batchWrite": "ConfigWriteResponse",
}


# These stable protocol support types live in V2Types.swift rather than the v2
# schema bundle. Keeping the exception explicit prevents a raw JSON fallback.
RESPONSE_TYPE_OVERRIDES = {
    "fuzzyFileSearch": "FuzzyFileSearchResponse",
    "fuzzyFileSearch/sessionStart": "EmptyResponse",
    "fuzzyFileSearch/sessionUpdate": "EmptyResponse",
    "fuzzyFileSearch/sessionStop": "EmptyResponse",
}


# These methods have deeper public commands because sending them also mutates
# subscription ownership, submission intent, composite turn identity, or an
# epoch-bound operation handle. Their generated factory remains module-internal
# for those implementations to use.
SPECIALIZED_METHODS = frozenset({
    "thread/start",
    "thread/resume",
    "thread/fork",
    "thread/unsubscribe",
    "turn/start",
    "turn/steer",
    "turn/interrupt",
    "account/login/start",
    "account/login/cancel",
})


@dataclass(frozen=True)
class RequestRow:
    method: str
    case_name: str
    method_case: str
    parameter_kind: str
    parameter_type: str | None
    response_type: str


def schema_type_names(definitions: dict[str, object]) -> dict[str, str]:
    """Mirror the schema-type generator's deterministic Swift name table."""
    result: dict[str, str] = {}
    used: dict[str, int] = {}
    for name in sorted(definitions):
        base = "CodexSchema" + swift_type_suffix(name)
        count = used.get(base, 0)
        used[base] = count + 1
        result[name] = base if count == 0 else f"{base}{count + 1}"
    return result


def referenced_definition(schema: object) -> str | None:
    if not isinstance(schema, dict):
        return None
    ref = schema.get("$ref")
    if isinstance(ref, str) and ref.startswith("#/definitions/"):
        return ref.removeprefix("#/definitions/")
    return None


def nullable_referenced_definition(schema: object) -> str | None:
    if not isinstance(schema, dict):
        return None
    for key in ("anyOf", "oneOf"):
        arms = schema.get(key)
        if not isinstance(arms, list) or len(arms) != 2:
            continue
        refs = [referenced_definition(arm) for arm in arms]
        null_count = sum(
            1 for arm in arms if isinstance(arm, dict) and arm.get("type") == "null"
        )
        non_null_refs = [ref for ref in refs if ref is not None]
        if null_count == 1 and len(non_null_refs) == 1:
            return non_null_refs[0]
    return None


def classify_parameters(arm: dict) -> tuple[str, str | None]:
    properties = arm.get("properties")
    required = arm.get("required")
    if not isinstance(properties, dict) or not isinstance(required, list):
        raise ValueError("client request arm must declare properties and required")

    params = properties.get("params")
    if "params" in required:
        definition = referenced_definition(params)
        if definition is None:
            raise ValueError("required params must reference one schema definition")
        return "required", definition

    if isinstance(params, dict) and params.get("type") == "null":
        return "omitted", None

    definition = nullable_referenced_definition(params)
    if definition is not None:
        return "nullable", definition

    raise ValueError(
        "optional params must be either null-only (omitted on wire) or a nullable schema ref"
    )


def response_type(
    method: str,
    parameter_definition: str | None,
    definitions: dict[str, object],
    type_names: dict[str, str],
) -> str:
    hand_written = RESPONSE_TYPE_OVERRIDES.get(method)
    if hand_written is not None:
        return hand_written

    definition = RESPONSE_DEFINITION_OVERRIDES.get(method)
    if definition is None:
        if parameter_definition is None or not parameter_definition.endswith("Params"):
            raise ValueError(f"{method} needs an explicit response mapping")
        definition = parameter_definition.removesuffix("Params") + "Response"

    if definition not in definitions or definition not in type_names:
        raise ValueError(
            f"{method} maps to missing response definition {definition!r}"
        )
    return type_names[definition]


def load_requests(schema_dir: Path) -> list[RequestRow]:
    bundle = json.loads(
        (schema_dir / "codex_app_server_protocol.v2.schemas.json").read_text()
    )
    definitions = bundle.get("definitions")
    if not isinstance(definitions, dict):
        raise ValueError("schema bundle definitions must be an object")
    type_names = schema_type_names(definitions)

    client = json.loads((schema_dir / "ClientRequest.json").read_text())
    rows: list[RequestRow] = []
    seen_methods: set[str] = set()
    seen_cases: set[str] = set()
    for index, arm in enumerate(client.get("oneOf", [])):
        if not isinstance(arm, dict):
            raise ValueError(f"client request arm {index} must be an object")
        properties = arm.get("properties")
        if not isinstance(properties, dict):
            raise ValueError(f"client request arm {index} has no properties")
        method_values = properties.get("method", {}).get("enum", [])
        if not isinstance(method_values, list) or len(method_values) != 1:
            raise ValueError(f"client request arm {index} needs one method literal")
        method = method_values[0]
        if not isinstance(method, str):
            raise ValueError(f"client request arm {index} method must be a string")
        if method == "initialize":
            # Handshake ownership belongs exclusively to CodexSession.start().
            continue

        case_name = swift_type_suffix(method)
        method_case = swift_case(method)
        if method in seen_methods or case_name in seen_cases:
            raise ValueError(f"duplicate or colliding client request {method!r}")
        seen_methods.add(method)
        seen_cases.add(case_name)

        kind, parameter_definition = classify_parameters(arm)
        parameter_type = (
            type_names.get(parameter_definition) if parameter_definition is not None else None
        )
        if parameter_definition is not None and parameter_type is None:
            raise ValueError(
                f"{method} references missing parameter definition {parameter_definition!r}"
            )
        rows.append(
            RequestRow(
                method=method,
                case_name=case_name,
                method_case=method_case,
                parameter_kind=kind,
                parameter_type=parameter_type,
                response_type=response_type(
                    method,
                    parameter_definition,
                    definitions,
                    type_names,
                ),
            )
        )
    return rows


def emit_factory(row: RequestRow) -> str:
    access = "" if row.method in SPECIALIZED_METHODS else "public "
    result = f"CodexAppServerRequest<{row.response_type}>"
    lines = ["extension CodexRequest {"]
    if row.parameter_kind == "required":
        lines.extend([
            f"    {access}static func {row.method_case}(",
            f"        _ params: {row.parameter_type}",
            f"    ) -> {result} {{",
            f"        .required(method: .{row.method_case}, params: params)",
        ])
    elif row.parameter_kind == "omitted":
        lines.extend([
            f"    {access}static func {row.method_case}() -> {result} {{",
            f"        .omitted(method: .{row.method_case})",
        ])
    else:
        lines.extend([
            f"    {access}static func {row.method_case}(",
            "        _ params: CodexNullableRequestParameters<",
            f"            {row.parameter_type}",
            "        > = .omitted",
            f"    ) -> {result} {{",
            f"        .nullable(method: .{row.method_case}, params: params)",
        ])
    lines.extend(["    }", "}", ""])
    return "\n".join(lines)


def emit_inventory(rows: list[RequestRow]) -> str:
    omitted = [row for row in rows if row.parameter_kind == "omitted"]
    nullable = [row for row in rows if row.parameter_kind == "nullable"]
    specialized = [row for row in rows if row.method in SPECIALIZED_METHODS]
    lines = [
        "public extension CodexRequest {",
        f"    static let generatedMethodCount = {len(rows)}",
        "    static let supportedMethods: Set<CodexAppServerClientMethod> = [",
    ]
    lines.extend(f"        .{row.method_case}," for row in rows)
    lines.extend(
        [
            "    ]",
            "    static let omittedParameterMethods: Set<CodexAppServerClientMethod> = [",
        ]
    )
    lines.extend(f"        .{row.method_case}," for row in omitted)
    lines.extend(
        [
            "    ]",
            "    static let nullableParameterMethods: Set<CodexAppServerClientMethod> = [",
        ]
    )
    lines.extend(f"        .{row.method_case}," for row in nullable)
    lines.extend(
        [
            "    ]",
            "    static let specializedMethods: Set<CodexAppServerClientMethod> = [",
        ]
    )
    lines.extend(f"        .{row.method_case}," for row in specialized)
    lines.extend(["    ]", "}", ""])
    return "\n".join(lines)


def emit_session_extension() -> str:
    return """public extension CodexSession {
    /// Performs one typed request through the session's ordered JSON-RPC seam.
    /// Stateful responses are committed to canonical state before this method
    /// returns; callers can query the response's entities immediately.
    func perform<Response: Decodable & Sendable>(
        _ request: CodexAppServerRequest<Response>
    ) async throws -> Response {
        let result = try await perform(
            method: request.method,
            params: try request.encodeParameters()
        )
        return try result.decode(Response.self)
    }
}
"""


def generate(schema_dir: Path) -> str:
    rows = load_requests(schema_dir)
    output = HEADER
    output += "".join(emit_factory(row) for row in rows)
    output += emit_inventory(rows)
    output += emit_session_extension()
    return output


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--schema-dir", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    output = generate(args.schema_dir)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(output)
    print(f"typed requests: {len(load_requests(args.schema_dir))} methods")


if __name__ == "__main__":
    main()
