#!/usr/bin/env python3
"""Generate Swift raw schema model aliases from Codex app-server JSON schemas."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


HEADER = """// Generated by Tools/generate_app_server_schema_types.py. Do not edit by hand.
import Foundation

public struct CodexAppServerSchemaValue: Codable, Sendable, Equatable {
    public var rawValue: CodexJSONValue

    public init(_ rawValue: CodexJSONValue = .dictionary([:])) {
        self.rawValue = rawValue
    }

    public init(from decoder: Decoder) throws {
        self.rawValue = try CodexJSONValue(from: decoder)
    }

    public func encode(to encoder: Encoder) throws {
        try rawValue.encode(to: encoder)
    }
}

public struct CodexAppServerSchemaDefinition: Sendable, Equatable {
    public let name: String
    public let typeName: String
}

"""


def swift_type_suffix(name: str) -> str:
    parts = [part for part in re.split(r"[^A-Za-z0-9]+", name) if part]
    if not parts:
        return "Unnamed"
    suffix = "".join(part[:1].upper() + part[1:] for part in parts)
    if suffix[:1].isdigit():
        suffix = "_" + suffix
    return suffix


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--schema-dir", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    bundle = json.loads((args.schema_dir / "codex_app_server_protocol.v2.schemas.json").read_text())
    definitions = bundle.get("definitions", {})
    if not isinstance(definitions, dict):
        raise ValueError("schema bundle definitions must be an object")

    rows: list[tuple[str, str]] = []
    used: dict[str, int] = {}
    for name in definitions:
        base = "CodexSchema" + swift_type_suffix(name)
        count = used.get(base, 0)
        used[base] = count + 1
        type_name = base if count == 0 else f"{base}{count + 1}"
        rows.append((name, type_name))

    v2_files = sorted(path.name for path in (args.schema_dir / "v2").glob("*.json"))

    output = HEADER
    for _, type_name in rows:
        output += f"public typealias {type_name} = CodexAppServerSchemaValue\n"

    output += "\npublic enum CodexAppServerSchemaInventory {\n"
    output += f"    public static let definitionCount = {len(rows)}\n"
    output += f"    public static let v2SchemaFileCount = {len(v2_files)}\n"
    output += "    public static let definitions: [CodexAppServerSchemaDefinition] = [\n"
    for name, type_name in rows:
        output += f"        CodexAppServerSchemaDefinition(name: {json.dumps(name)}, typeName: {json.dumps(type_name)}),\n"
    output += "    ]\n"
    output += "    public static let v2SchemaFiles: [String] = [\n"
    for file_name in v2_files:
        output += f"        {json.dumps(file_name)},\n"
    output += "    ]\n"
    output += "}\n"

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(output)


if __name__ == "__main__":
    main()
