#!/usr/bin/env python3
"""Generate Swift method enums from Codex app-server JSON schemas."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from swift_naming import split_identifier, swift_word


HEADER = """// Generated by Tools/generate_app_server_methods.py. Do not edit by hand.
import Foundation

"""


def load_methods(path: Path) -> list[str]:
    data = json.loads(path.read_text())
    methods: list[str] = []
    for arm in data.get("oneOf", []):
        enum_values = arm.get("properties", {}).get("method", {}).get("enum", [])
        if enum_values:
            methods.append(enum_values[0])
    return methods


def swift_case(method: str) -> str:
    parts = split_identifier(method)
    if not parts:
        raise ValueError(f"cannot build Swift case for method {method!r}")
    first = parts[0][:1].lower() + parts[0][1:]
    rest = [swift_word(part) for part in parts[1:]]
    name = first + "".join(rest)
    if name in {"case", "default", "enum", "func", "import", "init", "let", "public", "struct", "switch", "var"}:
        name = f"`{name}`"
    return name


def emit_enum(name: str, methods: list[str]) -> str:
    seen_cases: dict[str, str] = {}
    lines = [f"public enum {name}: String, CaseIterable, Codable, Sendable {{"]
    for method in methods:
        case_name = swift_case(method)
        if case_name in seen_cases:
            raise ValueError(f"case collision {case_name}: {seen_cases[case_name]} and {method}")
        seen_cases[case_name] = method
        lines.append(f"    case {case_name} = \"{method}\"")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--schema-dir", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    client = load_methods(args.schema_dir / "ClientRequest.json")
    notifications = load_methods(args.schema_dir / "ServerNotification.json")
    requests = load_methods(args.schema_dir / "ServerRequest.json")

    output = HEADER
    output += emit_enum("CodexAppServerClientMethod", client)
    output += emit_enum("CodexAppServerNotificationMethod", notifications)
    output += emit_enum("CodexAppServerServerRequestMethod", requests)
    output += "public enum CodexAppServerProtocolInventory {\n"
    output += f"    public static let clientMethodCount = {len(client)}\n"
    output += f"    public static let notificationMethodCount = {len(notifications)}\n"
    output += f"    public static let serverRequestMethodCount = {len(requests)}\n"
    output += "}\n"

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(output)


if __name__ == "__main__":
    main()
