#!/usr/bin/env python3
"""Generate the runtime compatibility constant from Tools/UPSTREAM_VERSION."""

from __future__ import annotations

import argparse
import pathlib
import re


VERSION_PATTERN = re.compile(r"^codex-cli\s+(\S+)\s*$")


def render(version_file: pathlib.Path) -> str:
    descriptor = version_file.read_text(encoding="utf-8").strip()
    match = VERSION_PATTERN.fullmatch(descriptor)
    if match is None:
        raise ValueError(
            f"{version_file} must contain exactly 'codex-cli <version>'; got {descriptor!r}"
        )
    version = match.group(1)
    return f'''// Generated by Tools/generate_pinned_runtime_version.py. Do not edit by hand.

/// Runtime identity compiled into the SDK from `Tools/UPSTREAM_VERSION`.
public enum CodexPinnedRuntime {{
    public static let package = "codex-cli"
    public static let version = "{version}"
    public static let descriptor = "codex-cli {version}"
}}
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--version-file", required=True, type=pathlib.Path)
    parser.add_argument("--out", required=True, type=pathlib.Path)
    args = parser.parse_args()
    args.out.write_text(render(args.version_file), encoding="utf-8")


if __name__ == "__main__":
    main()
