#!/usr/bin/env python3
"""Generate Swift raw schema model aliases from Codex app-server JSON schemas."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


HEADER = """// Generated by Tools/generate_app_server_schema_types.py. Do not edit by hand.
import Foundation

public struct CodexAppServerSchemaValue: Codable, Sendable, Equatable {
    public var rawValue: CodexJSONValue

    public init(_ rawValue: CodexJSONValue = .dictionary([:])) {
        self.rawValue = rawValue
    }

    public init(from decoder: Decoder) throws {
        self.rawValue = try CodexJSONValue(from: decoder)
    }

    public func encode(to encoder: Encoder) throws {
        try rawValue.encode(to: encoder)
    }
}

public struct CodexAppServerSchemaDefinition: Sendable, Equatable {
    public let name: String
    public let typeName: String
}

public struct CodexAppServerMethodSchemaDefinition: Sendable, Equatable {
    public let method: String
    public let definitionName: String
    public let typeName: String
}

"""

ACRONYMS = {
    "api": "API",
    "chatgpt": "ChatGPT",
    "db": "DB",
    "fs": "FS",
    "gpt": "GPT",
    "id": "ID",
    "ids": "IDs",
    "mcp": "MCP",
    "oauth": "OAuth",
    "openai": "OpenAI",
    "pty": "PTY",
    "rpc": "RPC",
}


def split_identifier(value: str) -> list[str]:
    pieces: list[str] = []
    for part in re.split(r"[^A-Za-z0-9]+", value):
        if not part:
            continue
        pieces.extend(re.findall(r"[A-Z]?\d+|[A-Z]+(?=[A-Z][a-z]|$)|[A-Z]?[a-z]+", part))
    return pieces


def swift_word(part: str) -> str:
    return ACRONYMS.get(part.lower(), part[:1].upper() + part[1:])


def swift_type_suffix(name: str) -> str:
    parts = split_identifier(name)
    if not parts:
        return "Unnamed"
    suffix = "".join(swift_word(part) for part in parts)
    if suffix[:1].isdigit():
        suffix = "_" + suffix
    return suffix


def load_method_param_refs(path: Path, type_names: dict[str, str]) -> list[tuple[str, str, str]]:
    data = json.loads(path.read_text())
    rows: list[tuple[str, str, str]] = []
    for arm in data.get("oneOf", []):
        properties = arm.get("properties", {})
        enum_values = properties.get("method", {}).get("enum", [])
        ref = properties.get("params", {}).get("$ref")
        if not enum_values or not isinstance(ref, str) or not ref.startswith("#/definitions/"):
            continue
        definition_name = ref.removeprefix("#/definitions/")
        type_name = type_names.get(definition_name, "")
        rows.append((enum_values[0], definition_name, type_name))
    return rows


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--schema-dir", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    bundle = json.loads((args.schema_dir / "codex_app_server_protocol.v2.schemas.json").read_text())
    definitions = bundle.get("definitions", {})
    if not isinstance(definitions, dict):
        raise ValueError("schema bundle definitions must be an object")

    rows: list[tuple[str, str]] = []
    used: dict[str, int] = {}
    for name in definitions:
        base = "CodexSchema" + swift_type_suffix(name)
        count = used.get(base, 0)
        used[base] = count + 1
        type_name = base if count == 0 else f"{base}{count + 1}"
        rows.append((name, type_name))

    type_names = dict(rows)

    client_params = load_method_param_refs(args.schema_dir / "ClientRequest.json", type_names)
    notification_payloads = load_method_param_refs(args.schema_dir / "ServerNotification.json", type_names)
    server_request_params = load_method_param_refs(args.schema_dir / "ServerRequest.json", type_names)

    v2_files = sorted(path.name for path in (args.schema_dir / "v2").glob("*.json"))

    output = HEADER
    for _, type_name in rows:
        output += f"public typealias {type_name} = CodexAppServerSchemaValue\n"

    output += "\npublic enum CodexAppServerSchemaInventory {\n"
    output += f"    public static let definitionCount = {len(rows)}\n"
    output += f"    public static let v2SchemaFileCount = {len(v2_files)}\n"
    output += "    public static let definitions: [CodexAppServerSchemaDefinition] = [\n"
    for name, type_name in rows:
        output += f"        CodexAppServerSchemaDefinition(name: {json.dumps(name)}, typeName: {json.dumps(type_name)}),\n"
    output += "    ]\n"
    output += f"    public static let clientRequestParamCount = {len(client_params)}\n"
    output += f"    public static let notificationPayloadCount = {len(notification_payloads)}\n"
    output += f"    public static let serverRequestParamCount = {len(server_request_params)}\n"
    output += "    public static let clientRequestParams: [CodexAppServerMethodSchemaDefinition] = [\n"
    for method, definition_name, type_name in client_params:
        output += f"        CodexAppServerMethodSchemaDefinition(method: {json.dumps(method)}, definitionName: {json.dumps(definition_name)}, typeName: {json.dumps(type_name)}),\n"
    output += "    ]\n"
    output += "    public static let notificationPayloads: [CodexAppServerMethodSchemaDefinition] = [\n"
    for method, definition_name, type_name in notification_payloads:
        output += f"        CodexAppServerMethodSchemaDefinition(method: {json.dumps(method)}, definitionName: {json.dumps(definition_name)}, typeName: {json.dumps(type_name)}),\n"
    output += "    ]\n"
    output += "    public static let serverRequestParams: [CodexAppServerMethodSchemaDefinition] = [\n"
    for method, definition_name, type_name in server_request_params:
        output += f"        CodexAppServerMethodSchemaDefinition(method: {json.dumps(method)}, definitionName: {json.dumps(definition_name)}, typeName: {json.dumps(type_name)}),\n"
    output += "    ]\n"
    output += "    public static let clientRequestParamByMethod: [String: CodexAppServerMethodSchemaDefinition] = Dictionary(uniqueKeysWithValues: clientRequestParams.map { ($0.method, $0) })\n"
    output += "    public static let notificationPayloadByMethod: [String: CodexAppServerMethodSchemaDefinition] = Dictionary(uniqueKeysWithValues: notificationPayloads.map { ($0.method, $0) })\n"
    output += "    public static let serverRequestParamByMethod: [String: CodexAppServerMethodSchemaDefinition] = Dictionary(uniqueKeysWithValues: serverRequestParams.map { ($0.method, $0) })\n"
    output += "    public static let v2SchemaFiles: [String] = [\n"
    for file_name in v2_files:
        output += f"        {json.dumps(file_name)},\n"
    output += "    ]\n"
    output += "}\n"
    output += "\npublic extension CodexAppServerNotificationMethod {\n"
    output += "    var schemaDefinition: CodexAppServerMethodSchemaDefinition? {\n"
    output += "        CodexAppServerSchemaInventory.notificationPayloadByMethod[rawValue]\n"
    output += "    }\n"
    output += "}\n"
    output += "\npublic extension CodexAppServerClientMethod {\n"
    output += "    var paramsSchemaDefinition: CodexAppServerMethodSchemaDefinition? {\n"
    output += "        CodexAppServerSchemaInventory.clientRequestParamByMethod[rawValue]\n"
    output += "    }\n"
    output += "}\n"
    output += "\npublic extension CodexAppServerServerRequestMethod {\n"
    output += "    var paramsSchemaDefinition: CodexAppServerMethodSchemaDefinition? {\n"
    output += "        CodexAppServerSchemaInventory.serverRequestParamByMethod[rawValue]\n"
    output += "    }\n"
    output += "}\n"

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(output)


if __name__ == "__main__":
    main()
